app:
    resource: '@AppBundle/Controller/'
    type: annotation

site:
    resource: '@AppBundle/Resources/config/routing.yml'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"